#include "services/settings_service.h"

#include <errno.h>

#include <glib.h>
#include <glib/gstdio.h>

struct _BsSettingsService {
  BsStateStore *store;
  char *config_path;
  char *state_path;
  BsShellConfig shell_config;
  bool dirty_state;
};

static bool
bs_settings_service_ensure_parent_dir(const char *path, GError **error) {
  g_autofree char *parent = NULL;

  if (path == NULL || *path == '\0') {
    return true;
  }

  parent = g_path_get_dirname(path);
  if (parent == NULL || g_strcmp0(parent, ".") == 0) {
    return true;
  }

  if (g_mkdir_with_parents(parent, 0700) != 0) {
    g_set_error(error,
                G_FILE_ERROR,
                g_file_error_from_errno(errno),
                "failed to create parent directory for %s",
                path);
    return false;
  }

  return true;
}

static char *
bs_settings_service_build_config_stub(const BsShellConfig *config) {
  GString *content = g_string_new("# bit_shell config.toml (stub generated by core)\n\n");

  g_string_append(content, "[shell]\n");
  g_string_append_printf(content, "auto_reconnect_niri = %s\n", config->auto_reconnect_niri ? "true" : "false");
  g_string_append_printf(content, "tray_watcher_name = \"%s\"\n", config->tray_watcher_name != NULL ? config->tray_watcher_name : "");
  g_string_append_printf(content, "primary_output = \"%s\"\n\n", config->primary_output != NULL ? config->primary_output : "");

  g_string_append(content, "[bar]\n");
  g_string_append_printf(content, "height_px = %u\n", config->bar.height_px);
  g_string_append_printf(content, "show_workspace_strip = %s\n", config->bar.show_workspace_strip ? "true" : "false");
  g_string_append_printf(content, "show_focused_title = %s\n", config->bar.show_focused_title ? "true" : "false");
  g_string_append_printf(content, "show_tray = %s\n", config->bar.show_tray ? "true" : "false");
  g_string_append_printf(content, "show_clock = %s\n\n", config->bar.show_clock ? "true" : "false");

  g_string_append(content, "[dock]\n");
  g_string_append_printf(content, "icon_size_px = %u\n", config->dock.icon_size_px);
  g_string_append_printf(content, "spacing_px = %u\n", config->dock.spacing_px);
  g_string_append_printf(content, "display_mode = \"%s\"\n", bs_dock_display_mode_to_string(config->dock.display_mode));
  g_string_append_printf(content, "enable_magnification = %s\n", config->dock.enable_magnification ? "true" : "false");
  g_string_append_printf(content, "center_on_primary_output = %s\n\n", config->dock.center_on_primary_output ? "true" : "false");

  g_string_append(content, "[launchpad]\n");
  g_string_append_printf(content, "resident = %s\n", config->launchpad.resident ? "true" : "false");
  g_string_append_printf(content, "grid_icon_size_px = %u\n", config->launchpad.grid_icon_size_px);
  g_string_append_printf(content, "max_recent_apps = %u\n", config->launchpad.max_recent_apps);
  g_string_append_printf(content, "show_categories = %s\n", config->launchpad.show_categories ? "true" : "false");

  return g_string_free(content, false);
}

static char *
bs_settings_service_build_state_stub(BsSettingsService *service) {
  GString *content = g_string_new(NULL);

  g_string_append_printf(content,
                         "{\n  \"generation\": %" G_GUINT64_FORMAT ",\n  \"settings_dirty\": %s,\n  \"pinned_apps\": [],\n  \"recent_apps\": [],\n  \"favorites\": [],\n  \"recent_workspaces\": []\n}\n",
                         bs_state_store_generation(service->store),
                         service->dirty_state ? "true" : "false");
  return g_string_free(content, false);
}

static bool
bs_settings_service_ensure_stub_file(const char *path,
                                     const char *contents,
                                     GError **error) {
  if (path == NULL || *path == '\0') {
    return true;
  }

  if (!bs_settings_service_ensure_parent_dir(path, error)) {
    return false;
  }

  if (g_file_test(path, G_FILE_TEST_EXISTS)) {
    return true;
  }

  return g_file_set_contents(path, contents, -1, error);
}

BsSettingsService *
bs_settings_service_new(BsStateStore *store, const BsSettingsServiceConfig *config) {
  BsSettingsService *service = g_new0(BsSettingsService, 1);
  service->store = store;
  bs_shell_config_init_defaults(&service->shell_config);
  if (config != NULL && config->config_path != NULL) {
    service->config_path = g_strdup(config->config_path);
    g_free(service->shell_config.paths.config_path);
    service->shell_config.paths.config_path = g_strdup(config->config_path);
  }
  if (config != NULL && config->state_path != NULL) {
    service->state_path = g_strdup(config->state_path);
    g_free(service->shell_config.paths.state_path);
    service->shell_config.paths.state_path = g_strdup(config->state_path);
  }
  return service;
}

void
bs_settings_service_free(BsSettingsService *service) {
  if (service == NULL) {
    return;
  }

  g_free(service->config_path);
  g_free(service->state_path);
  bs_shell_config_clear(&service->shell_config);
  g_free(service);
}

bool
bs_settings_service_load(BsSettingsService *service, GError **error) {
  g_autofree char *config_stub = NULL;
  g_autofree char *state_stub = NULL;
  g_autofree char *config_contents = NULL;
  g_autofree char *state_contents = NULL;

  g_return_val_if_fail(service != NULL, false);

  config_stub = bs_settings_service_build_config_stub(&service->shell_config);
  state_stub = bs_settings_service_build_state_stub(service);

  if (!bs_settings_service_ensure_stub_file(service->config_path, config_stub, error)) {
    return false;
  }
  if (!bs_settings_service_ensure_stub_file(service->state_path, state_stub, error)) {
    return false;
  }

  if (service->config_path != NULL) {
    (void) g_file_get_contents(service->config_path, &config_contents, NULL, NULL);
  }
  if (service->state_path != NULL) {
    (void) g_file_get_contents(service->state_path, &state_contents, NULL, NULL);
  }

  if (config_contents != NULL && *config_contents != '\0') {
    g_message("[bit_shelld] settings load stub read config from %s (parser TODO)", service->config_path);
  }
  if (state_contents != NULL && *state_contents != '\0') {
    g_message("[bit_shelld] settings load stub read state from %s (parser TODO)", service->state_path);
  }

  bs_state_store_mark_topic_changed(service->store, BS_TOPIC_SETTINGS);
  return true;
}

bool
bs_settings_service_flush(BsSettingsService *service, GError **error) {
  g_autofree char *state_stub = NULL;

  g_return_val_if_fail(service != NULL, false);

  state_stub = bs_settings_service_build_state_stub(service);
  if (service->state_path != NULL) {
    if (!bs_settings_service_ensure_parent_dir(service->state_path, error)) {
      return false;
    }
    if (!g_file_set_contents(service->state_path, state_stub, -1, error)) {
      return false;
    }
  }

  service->dirty_state = false;
  return true;
}

const BsShellConfig *
bs_settings_service_shell_config(const BsSettingsService *service) {
  g_return_val_if_fail(service != NULL, NULL);
  return &service->shell_config;
}

void
bs_settings_service_mark_state_dirty(BsSettingsService *service) {
  g_return_if_fail(service != NULL);
  service->dirty_state = true;
}
