#include "services/settings_service.h"

#include <errno.h>

#include <glib.h>
#include <glib/gstdio.h>
#include <json-glib/json-glib.h>

struct _BsSettingsService {
  BsStateStore *store;
  char *config_path;
  char *state_path;
  BsShellConfig shell_config;
  bool dirty_state;
};

static bool
bs_settings_service_ensure_parent_dir(const char *path, GError **error) {
  g_autofree char *parent = NULL;

  if (path == NULL || *path == '\0') {
    return true;
  }

  parent = g_path_get_dirname(path);
  if (parent == NULL || g_strcmp0(parent, ".") == 0) {
    return true;
  }

  if (g_mkdir_with_parents(parent, 0700) != 0) {
    g_set_error(error,
                G_FILE_ERROR,
                g_file_error_from_errno(errno),
                "failed to create parent directory for %s",
                path);
    return false;
  }

  return true;
}

static GPtrArray *
bs_settings_service_dup_pinned_apps(BsSettingsService *service) {
  BsSnapshot *snapshot = NULL;
  GPtrArray *copy = NULL;

  g_return_val_if_fail(service != NULL, NULL);

  snapshot = bs_state_store_snapshot(service->store);
  copy = g_ptr_array_new_with_free_func(g_free);
  if (snapshot == NULL || snapshot->pinned_app_ids == NULL) {
    return copy;
  }

  for (guint i = 0; i < snapshot->pinned_app_ids->len; i++) {
    const char *desktop_id = g_ptr_array_index(snapshot->pinned_app_ids, i);
    if (desktop_id != NULL && *desktop_id != '\0') {
      g_ptr_array_add(copy, g_strdup(desktop_id));
    }
  }

  return copy;
}

static void
bs_settings_service_append_string_array_json(GString *content, GPtrArray *values) {
  g_return_if_fail(content != NULL);

  g_string_append(content, "[");
  if (values != NULL) {
    for (guint i = 0; i < values->len; i++) {
      char *escaped = NULL;
      const char *value = g_ptr_array_index(values, i);

      if (i > 0) {
        g_string_append(content, ",");
      }

      escaped = g_strescape(value != NULL ? value : "", NULL);
      g_string_append_printf(content, "\"%s\"", escaped != NULL ? escaped : "");
      g_free(escaped);
    }
  }
  g_string_append(content, "]");
}

static bool
bs_settings_service_parse_state(BsSettingsService *service,
                                const char *contents,
                                GError **error) {
  g_autoptr(JsonParser) parser = NULL;
  g_autoptr(GPtrArray) pinned_app_ids = NULL;
  g_autoptr(GHashTable) seen = NULL;
  JsonNode *root = NULL;
  JsonObject *root_object = NULL;
  JsonArray *pinned_apps = NULL;

  g_return_val_if_fail(service != NULL, false);

  if (contents == NULL || *contents == '\0') {
    bs_state_store_begin_update(service->store);
    bs_state_store_replace_pinned_app_ids(service->store, NULL);
    bs_state_store_replace_dock_config(service->store, &service->shell_config.dock);
    bs_state_store_finish_update(service->store);
    return true;
  }

  parser = json_parser_new();
  if (!json_parser_load_from_data(parser, contents, -1, error)) {
    return false;
  }

  root = json_parser_get_root(parser);
  if (root == NULL || !JSON_NODE_HOLDS_OBJECT(root)) {
    g_set_error(error, G_IO_ERROR, G_IO_ERROR_INVALID_DATA, "state.json root is not an object");
    return false;
  }

  root_object = json_node_get_object(root);
  pinned_app_ids = g_ptr_array_new_with_free_func(g_free);
  seen = g_hash_table_new(g_str_hash, g_str_equal);

  if (json_object_has_member(root_object, "pinned_apps")) {
    JsonNode *pinned_node = json_object_get_member(root_object, "pinned_apps");

    if (!JSON_NODE_HOLDS_ARRAY(pinned_node)) {
      g_set_error(error, G_IO_ERROR, G_IO_ERROR_INVALID_DATA, "state.json pinned_apps is not an array");
      return false;
    }

    pinned_apps = json_node_get_array(pinned_node);
    for (guint i = 0; i < json_array_get_length(pinned_apps); i++) {
      const char *desktop_id = json_array_get_string_element(pinned_apps, i);

      if (desktop_id == NULL || *desktop_id == '\0') {
        continue;
      }
      if (g_hash_table_contains(seen, desktop_id)) {
        continue;
      }

      g_hash_table_add(seen, (gpointer) desktop_id);
      g_ptr_array_add(pinned_app_ids, g_strdup(desktop_id));
    }
  }

  bs_state_store_begin_update(service->store);
  bs_state_store_replace_pinned_app_ids(service->store, pinned_app_ids);
  bs_state_store_replace_dock_config(service->store, &service->shell_config.dock);
  bs_state_store_finish_update(service->store);
  return true;
}

static char *
bs_settings_service_build_config_stub(const BsShellConfig *config) {
  GString *content = g_string_new("# bit_shell config.toml (stub generated by core)\n\n");

  g_string_append(content, "[shell]\n");
  g_string_append_printf(content, "auto_reconnect_niri = %s\n", config->auto_reconnect_niri ? "true" : "false");
  g_string_append_printf(content, "tray_watcher_name = \"%s\"\n", config->tray_watcher_name != NULL ? config->tray_watcher_name : "");
  g_string_append_printf(content, "primary_output = \"%s\"\n\n", config->primary_output != NULL ? config->primary_output : "");

  g_string_append(content, "[bar]\n");
  g_string_append_printf(content, "height_px = %u\n", config->bar.height_px);
  g_string_append_printf(content, "show_workspace_strip = %s\n", config->bar.show_workspace_strip ? "true" : "false");
  g_string_append_printf(content, "show_focused_title = %s\n", config->bar.show_focused_title ? "true" : "false");
  g_string_append_printf(content, "show_tray = %s\n", config->bar.show_tray ? "true" : "false");
  g_string_append_printf(content, "show_clock = %s\n\n", config->bar.show_clock ? "true" : "false");

  g_string_append(content, "[dock]\n");
  g_string_append_printf(content, "icon_size_px = %u\n", config->dock.icon_size_px);
  g_string_append_printf(content, "magnification_enabled = %s\n", config->dock.magnification_enabled ? "true" : "false");
  g_string_append_printf(content, "magnification_scale = %.2f\n", config->dock.magnification_scale);
  g_string_append_printf(content, "hover_range_max = %u\n", config->dock.hover_range_max);
  g_string_append_printf(content, "spacing_px = %u\n", config->dock.spacing_px);
  g_string_append_printf(content, "bottom_margin_px = %u\n", config->dock.bottom_margin_px);
  g_string_append_printf(content, "show_running_indicator = %s\n", config->dock.show_running_indicator ? "true" : "false");
  g_string_append_printf(content, "animate_opening_apps = %s\n", config->dock.animate_opening_apps ? "true" : "false");
  g_string_append_printf(content, "display_mode = \"%s\"\n", bs_dock_display_mode_to_string(config->dock.display_mode));
  g_string_append_printf(content, "center_on_primary_output = %s\n\n", config->dock.center_on_primary_output ? "true" : "false");

  g_string_append(content, "[launchpad]\n");
  g_string_append_printf(content, "resident = %s\n", config->launchpad.resident ? "true" : "false");
  g_string_append_printf(content, "grid_icon_size_px = %u\n", config->launchpad.grid_icon_size_px);
  g_string_append_printf(content, "max_recent_apps = %u\n", config->launchpad.max_recent_apps);
  g_string_append_printf(content, "show_categories = %s\n", config->launchpad.show_categories ? "true" : "false");

  return g_string_free(content, false);
}

static char *
bs_settings_service_build_state_stub(BsSettingsService *service) {
  g_autoptr(GPtrArray) pinned_app_ids = NULL;
  GString *content = g_string_new(NULL);

  pinned_app_ids = bs_settings_service_dup_pinned_apps(service);
  g_string_append_printf(content,
                         "{\n  \"generation\": %" G_GUINT64_FORMAT ",\n  \"settings_dirty\": %s,\n  \"pinned_apps\": ",
                         bs_state_store_generation(service->store),
                         service->dirty_state ? "true" : "false");
  bs_settings_service_append_string_array_json(content, pinned_app_ids);
  g_string_append(content, ",\n  \"recent_apps\": [],\n  \"favorites\": [],\n  \"recent_workspaces\": []\n}\n");
  return g_string_free(content, false);
}

static bool
bs_settings_service_ensure_stub_file(const char *path,
                                     const char *contents,
                                     GError **error) {
  if (path == NULL || *path == '\0') {
    return true;
  }

  if (!bs_settings_service_ensure_parent_dir(path, error)) {
    return false;
  }

  if (g_file_test(path, G_FILE_TEST_EXISTS)) {
    return true;
  }

  return g_file_set_contents(path, contents, -1, error);
}

BsSettingsService *
bs_settings_service_new(BsStateStore *store, const BsSettingsServiceConfig *config) {
  BsSettingsService *service = g_new0(BsSettingsService, 1);
  service->store = store;
  bs_shell_config_init_defaults(&service->shell_config);
  if (config != NULL && config->config_path != NULL) {
    service->config_path = g_strdup(config->config_path);
    g_free(service->shell_config.paths.config_path);
    service->shell_config.paths.config_path = g_strdup(config->config_path);
  }
  if (config != NULL && config->state_path != NULL) {
    service->state_path = g_strdup(config->state_path);
    g_free(service->shell_config.paths.state_path);
    service->shell_config.paths.state_path = g_strdup(config->state_path);
  }
  return service;
}

void
bs_settings_service_free(BsSettingsService *service) {
  if (service == NULL) {
    return;
  }

  g_free(service->config_path);
  g_free(service->state_path);
  bs_shell_config_clear(&service->shell_config);
  g_free(service);
}

bool
bs_settings_service_load(BsSettingsService *service, GError **error) {
  g_autofree char *config_stub = NULL;
  g_autofree char *state_stub = NULL;
  g_autofree char *config_contents = NULL;
  g_autofree char *state_contents = NULL;

  g_return_val_if_fail(service != NULL, false);

  config_stub = bs_settings_service_build_config_stub(&service->shell_config);
  state_stub = bs_settings_service_build_state_stub(service);

  if (!bs_settings_service_ensure_stub_file(service->config_path, config_stub, error)) {
    return false;
  }
  if (!bs_settings_service_ensure_stub_file(service->state_path, state_stub, error)) {
    return false;
  }

  if (service->config_path != NULL) {
    (void) g_file_get_contents(service->config_path, &config_contents, NULL, NULL);
  }
  if (service->state_path != NULL) {
    (void) g_file_get_contents(service->state_path, &state_contents, NULL, NULL);
  }

  if (config_contents != NULL && *config_contents != '\0') {
    g_message("[bit_shelld] settings load stub read config from %s (parser TODO)", service->config_path);
  }
  return bs_settings_service_parse_state(service, state_contents, error);
}

bool
bs_settings_service_flush(BsSettingsService *service, GError **error) {
  g_autofree char *state_stub = NULL;

  g_return_val_if_fail(service != NULL, false);

  state_stub = bs_settings_service_build_state_stub(service);
  if (service->state_path != NULL) {
    if (!bs_settings_service_ensure_parent_dir(service->state_path, error)) {
      return false;
    }
    if (!g_file_set_contents(service->state_path, state_stub, -1, error)) {
      return false;
    }
  }

  service->dirty_state = false;
  return true;
}

const BsShellConfig *
bs_settings_service_shell_config(const BsSettingsService *service) {
  g_return_val_if_fail(service != NULL, NULL);
  return &service->shell_config;
}

void
bs_settings_service_mark_state_dirty(BsSettingsService *service) {
  g_return_if_fail(service != NULL);
  service->dirty_state = true;
}
